--
-- PostgreSQL database dump
--

\restrict SVrzPDlxlfLiC0TGGLaJ26lzwCWs04xojFxvIqy74Lkh8TXAiHLRgaX38xS1KN2

-- Dumped from database version 18.1 (Debian 18.1-1.pgdg12+2)
-- Dumped by pg_dump version 18.1 (Debian 18.1-2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance_attendance; Type: TABLE; Schema: public; Owner: hrms_max5_user
--

CREATE TABLE public.attendance_attendance (
    id bigint NOT NULL,
    date date NOT NULL,
    status character varying(255) NOT NULL,
    employee_id bigint NOT NULL
);


ALTER TABLE public.attendance_attendance OWNER TO hrms_max5_user;

--
-- Name: attendance_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_max5_user
--

ALTER TABLE public.attendance_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_employee; Type: TABLE; Schema: public; Owner: hrms_max5_user
--

CREATE TABLE public.employee_employee (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    department character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.employee_employee OWNER TO hrms_max5_user;

--
-- Name: employee_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: hrms_max5_user
--

ALTER TABLE public.employee_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: attendance_attendance; Type: TABLE DATA; Schema: public; Owner: hrms_max5_user
--

COPY public.attendance_attendance (id, date, status, employee_id) FROM stdin;
1	2026-01-18	Present	2
2	2026-01-18	Absent	1
3	2026-01-18	Present	3
4	2026-01-17	Absent	3
5	2026-01-17	Absent	4
6	2026-01-17	Absent	1
\.


--
-- Data for Name: employee_employee; Type: TABLE DATA; Schema: public; Owner: hrms_max5_user
--

COPY public.employee_employee (id, first_name, last_name, email, department, created_at, updated_at) FROM stdin;
1	manish	Panda	manish@gmail.com	Human Resources	2026-01-17 09:12:13.014521+00	2026-01-17 09:12:13.862197+00
2	silpa	sukla	silpa@gmail.com	Finance	2026-01-17 09:12:13.014521+00	2026-01-17 09:12:13.862197+00
3	mona	sina	mona@gmail.com	Human Resources	2026-01-17 09:13:26.554134+00	2026-01-17 09:13:26.554192+00
4	anish	Panda	anish123@gmail.com	Finance	2026-01-17 09:29:34.214479+00	2026-01-17 09:32:58.80632+00
6	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.02253+00	2026-01-20 15:34:13.022567+00
7	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.117359+00	2026-01-20 15:34:13.117376+00
8	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.147176+00	2026-01-20 15:34:13.147188+00
9	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.206497+00	2026-01-20 15:34:13.206511+00
10	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.237349+00	2026-01-20 15:34:13.237364+00
11	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.358963+00	2026-01-20 15:34:13.358975+00
12	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.389225+00	2026-01-20 15:34:13.389236+00
13	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.480126+00	2026-01-20 15:34:13.480139+00
14	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.515306+00	2026-01-20 15:34:13.515323+00
15	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.545602+00	2026-01-20 15:34:13.545614+00
16	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.93036+00	2026-01-20 15:34:13.930374+00
17	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:13.96527+00	2026-01-20 15:34:13.965278+00
18	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:14.002241+00	2026-01-20 15:34:14.00225+00
19	ssfsegf	dsds	scdsz@gd.com	Human Resources	2026-01-20 15:34:14.03123+00	2026-01-20 15:34:14.031239+00
\.


--
-- Name: attendance_attendance_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_max5_user
--

SELECT pg_catalog.setval('public.attendance_attendance_id_seq', 6, true);


--
-- Name: employee_employee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: hrms_max5_user
--

SELECT pg_catalog.setval('public.employee_employee_id_seq', 19, true);


--
-- Name: attendance_attendance attendance_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_max5_user
--

ALTER TABLE ONLY public.attendance_attendance
    ADD CONSTRAINT attendance_attendance_pkey PRIMARY KEY (id);


--
-- Name: employee_employee employee_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: hrms_max5_user
--

ALTER TABLE ONLY public.employee_employee
    ADD CONSTRAINT employee_employee_pkey PRIMARY KEY (id);


--
-- Name: attendance_attendance_employee_id_63b4db5a; Type: INDEX; Schema: public; Owner: hrms_max5_user
--

CREATE INDEX attendance_attendance_employee_id_63b4db5a ON public.attendance_attendance USING btree (employee_id);


--
-- Name: attendance_attendance attendance_attendanc_employee_id_63b4db5a_fk_employee_; Type: FK CONSTRAINT; Schema: public; Owner: hrms_max5_user
--

ALTER TABLE ONLY public.attendance_attendance
    ADD CONSTRAINT attendance_attendanc_employee_id_63b4db5a_fk_employee_ FOREIGN KEY (employee_id) REFERENCES public.employee_employee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict SVrzPDlxlfLiC0TGGLaJ26lzwCWs04xojFxvIqy74Lkh8TXAiHLRgaX38xS1KN2

