# Generated by Django 6.0.1 on 2026-01-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=255)),
                ('employee', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee')),
            ],
        ),
    ]
